DROP TABLE STUDENT CASCADE CONSTRAINTS;

DROP TABLE CLASS;

CREATE TABLE STUDENT (
  STDNO INT NOT NULL,
  STDNAME VARCHAR2(100),
  PRIMARY KEY (STDNO)
);

CREATE TABLE CLASS (
  CLSID INT NOT NULL,
  STDNO INT NOT NULL,
  CLSNAME VARCHAR2(100),
  PFNAME VARCHAR2(100),
  PRIMARY KEY (CLSID),
  FOREIGN KEY (STDNO) REFERENCES STUDENT(STDNO)
);


CREATE SEQUENCE class_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;